name: GitHub Readme Streak Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Generate Streak Stats Card
        uses: denvercoder1/github-readme-streak-stats-action@v2
        with:
          # This maps your custom secret cleanly
          token: ${{ secrets.GH_TOKEN }}

      - name: Deploy Changes
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
